[hostname]
ssh_only = false
style = "bold fg:166"

[username]
disabled = false
show_always = true

[git_branch]
style = "bold fg:37"

[directory]
truncation_length = 7
use_logical_path = true
truncate_to_repo = false
style = "bold fg:64"

[package]
disabled = true

[ruby]
disabled = true

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true
